---
- name: Update Oracle Linux Systems
  hosts: all
  become: yes
  tasks:
    - name: Update all packages (security only)
      dnf:
        name: '*'
        state: latest
        update_cache: yes
        security: yes
      
    - name: Clean up packages
      dnf:
        autoremove: yes
        clean: all
      
    - name: Check if reboot needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      
    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible after updates"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 30
      when: reboot_required.stat.exists
