---
- name: Simple package update
  hosts: oracle
  become: true

  tasks:
    - name: Update all packages (simple)
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      register: update_result
      changed_when: update_result.stdout != ""