---
- name: Update Oracle Linux Systems
  hosts: oracle
  gather_facts: false  # Disable automatic fact gathering
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_facts is defined

    - name: Clean up packages
      dnf:
        autoremove: yes
        clean: all
      when: ansible_facts is defined
