---
- name: Oracle Linux ARM System Maintenance
  hosts: all
  # Completely disable fact gathering and Python usage
  gather_facts: false
  become: true

  tasks:
    # 1. Directly clean package cache
    - name: Clean DNF cache
      ansible.builtin.raw: dnf clean all
      args:
        executable: /bin/bash
      changed_when: false

    # 2. Check for updates (returns 100 when updates available)
    - name: Check for available updates
      ansible.builtin.raw: dnf check-update
      args:
        executable: /bin/bash
      register: updates_available
      ignore_errors: true
      changed_when: false

    # 3. Apply updates if available (using raw command)
    - name: Apply system updates
      ansible.builtin.raw: dnf update -y
      args:
        executable: /bin/bash
      when: updates_available.rc == 100
      register: system_update
      # Only show as changed if updates were actually applied
      changed_when: "'Nothing to do' not in system_update.stdout"

    # 4. Clean up unused packages
    - name: Remove unused packages
      ansible.builtin.raw: dnf autoremove -y
      args:
        executable: /bin/bash
      when: updates_available.rc == 100
      changed_when: false

    # 5. Final status message
    - name: System status
      ansible.builtin.debug:
        msg: "{{ 'System updates were applied' if updates_available.rc == 100 else 'System is already up-to-date' }}"