---
- name: Oracle Linux ARM System Maintenance
  hosts: oracle
  # Disable automatic fact gathering to prevent Python conflicts
  gather_facts: false
  become: true

  tasks:
    # 1. First ensure proper Python is available
    - name: Verify Python 3 availability
      ansible.builtin.raw: |
        python3 -c 'import sys; print(sys.version_info.major)' || 
        python -c 'import sys; print(sys.version_info.major)'
      register: python_check
      changed_when: false
      ignore_errors: true

    # 2. Install Python 3 if missing (Oracle Linux ARM specific)
    - name: Install Python 3
      ansible.builtin.raw: |
        if ! command -v python3 >/dev/null; then
          if grep -q 'release 8' /etc/oracle-release; then
            sudo dnf install -y python39 python3-dnf
            sudo alternatives --set python /usr/bin/python3
          elif grep -q 'release 7' /etc/oracle-release; then
            sudo yum install -y python36 python3-libdnf
          fi
        fi
      when: python_check.failed
      args:
        executable: /bin/bash

    # 3. Manually set Python interpreter path
    - name: Set Python interpreter fact
      ansible.builtin.set_fact:
        ansible_python_interpreter: "/usr/bin/python3"

    # 4. Now run package updates (direct command approach)
    - name: Check for available updates
      ansible.builtin.command: /usr/bin/dnf check-update
      register: updates_available
      ignore_errors: true  # Returns 100 when updates exist
      changed_when: false

    - name: Apply system updates
      ansible.builtin.command: /usr/bin/dnf update -y
      when: updates_available.rc == 100
      register: system_update
      changed_when: "'Nothing to do' not in system_update.stdout"

    - name: Clean up packages
      ansible.builtin.command: /usr/bin/dnf autoremove -y
      when: updates_available.rc == 100
      changed_when: false

    - name: System status
      ansible.builtin.debug:
        msg: "{{ 'Updates were applied' if updates_available.rc == 100 else 'System was already up-to-date' }}"