---
- name: Update Oracle VM Servers
  hosts: oracle
  become: yes
  
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == "OracleLinux"
      
    - name: Reboot if required
      reboot:
        reboot_timeout: 3600
      when: ansible_distribution == "OracleLinux"
