---
- name: Update Oracle VM Servers
  hosts: oracle
  become: yes
  
  tasks:
    - name: Update all packages
      command: dnf update -y
      register: dnf_update
      changed_when: "No'No packages marked for update' not in dnf_update.stdout"
      
      
    - name: Reboot if required
      reboot:
        reboot_timeout: 3600
      
