---
- name: Update Oracle Linux Systems
  hosts: 132.145.145.198
  gather_facts: false  # Disable automatic fact gathering
  become: yes

  tasks:
    # First ensure Python is available
    - name: Install Python 3
      raw: dnf install -y python3
      register: python_install
      changed_when: python_install.rc == 0
      when: ansible_python_interpreter is not defined

    # Now manually gather facts
    - name: Gather facts
      setup:
      when: python_install is succeeded or ansible_python_interpreter is defined

    # Continue with your tasks
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_facts is defined

    - name: Clean up packages
      dnf:
        autoremove: yes
        clean: all
      when: ansible_facts is defined
