---
- name: Update Oracle VM Servers
  hosts: oracle
  become: yes
  
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python3.6
      
    - name: Reboot if required
      reboot:
        reboot_timeout: 3600
      
